name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      settings: "publishconf.py"
      python: "3.11"
